spring.application.name=habit_tracker
server.port = 8000

spring.datasource.url=jdbc:mysql://localhost:3306/habit_tracker
spring.datasource.username=root
spring.datasource.password=khanna2007
spring.jpa.hibernate.ddl-auto=update